### ISSUE TITLE
less css

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#158]
[It is possible to use vh minus pixels in a CSS calc](https://stackoverflow.com/questions/27256849/it-is-possible-to-use-vh-minus-pixels-in-a-css-calc)
错误的写法
```css
.container {
  min-height: calc(100vh - 150px);
}
```
正确的写法

```css
.container {
  min-height: calc(~"100vh - 150px");
}
```
Thanks to this link: [Less Aggressive Compilation with CSS3 calc](https://stackoverflow.com/questions/11972084/less-aggressive-compilation-with-css3-calc)
