### ISSUE TITLE
highlight text inside a textarea

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#199]
在textarea内高亮指定的文本.
![highlight](https://user-images.githubusercontent.com/1049271/38509476-8e68f0de-3c54-11e8-96c8-a9b59a35d415.jpg)

参考以下,然后自己和vue.js做了整合.
https://codersblock.com/blog/highlight-text-inside-a-textarea/

https://codepen.io/lonekorean/pen/gaLEMR

https://github.com/lonekorean/highlight-within-textarea

**Comment by uniquejava** [comment]
## 碰到的问题

1. 换行错位.
如下, 我的textarea需要减掉20px才好用.
```css
    .input-container, .backdrop {
      width: 98%;
      height: 6em;
    }

    textarea {
      width: calc(98% - 20px);
      height: 6em;
    }
```

2. 滚动条
我的高亮是在mouse over 某个tag时触发的, 此时.highlights中的文字被完全重绘了, 需要在mouseover事件中调用handleScroll方法, 而非在textarea的`@scroll`中触发.
