### ISSUE TITLE
nativescript

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#234]
## 搭建环境
在app store中搜索nativescript下载它的playground和preview两个app.
然后在 https://play.nativescript.org 写界面, 扫码运行.

## 得到原生组件的引用
见`https://github.com/nativescript-vue/nativescript-vue/issues/205`

```html
<ListView ref="listView" for="item in listOfItems" @itemTap="onItemTap">

this.$refs.listView.$el.nativeView.refresh();
```

Explanation:

* `this.$refs.list` - access to the "DOM" element that you tagged with `ref="listView"`
* `$el` - because the above is actually a Vue component internally, we have to access the `<native-list-view>` element, `$el` does this.
* `nativeView` - is the NativeScript view that is described in the linked docs.

## 一定不要在template中使用this.
```html
<!-- Buggy -->
<Label v-show="$index === 0" :text="this.useWatson ? 'watson' : 'local'"></Label>

<!-- Correct -->
<Label v-show="$index === 0" :text="useWatson ? 'watson' : 'local'"></Label>
```

## Blog
[styling](https://docs.nativescript.org/ui/styling) css类名不区分大小写.

[theme](https://docs.nativescript.org/ui/theme)

[Showing an Activity Indicator During Processing in NativeScript Apps](https://www.nativescript.org/blog/showing-an-activity-indicator-during-processing-in-nativescript-apps)

[Building a Simple Progressbar for your NativeScript App](https://www.nativescript.org/blog/building-a-simple-progressbar-for-your-nativescript-app)

### 使用feather icon
[icon button](https://docs.nativescript.org/ui/ns-ui-widgets/button)
[icon fonts](https://docs.nativescript.org/ui/icon-fonts)

在iconmoon网站上导入feathericon字库, generate > download 将生成的`icomoon.ttf`放到项目的app/fonts目录下.
定义样式
```css
.icon {
   font-family: 'icomoon';
   font-size: 48;
}
.btn-connect {
    margin-bottom: 15;
    width: 180;
    height: 180;
    border-radius: 100%;
    border-width: 1;
    border-color: #FFFFFF;
    font-family: 'icomoon';
    font-size: 64;
}
```
使用
```html
<Button class="btn-connect" :text="String.fromCharCode(0xe9b5)" />
<Label class="icon"  :text="String.fromCharCode(0xe930)" />
```
