### ISSUE TITLE
flutter watson stt

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#284]
https://speech-to-text-demo.mybluemix.net/

https://cloud.ibm.com/apidocs/speech-to-text/speech-to-text#websocket_methods

https://cloud.ibm.com/docs/speech-to-text?topic=speech-to-text-websockets#websockets

https://flutter.dev/docs/cookbook/networking/web-sockets

https://www.didierboelens.com/2018/06/web-sockets-build-a-real-time-game/

插件

```yaml
dependencies:
  flutter:
    sdk: flutter
  web_socket_channel: ^1.1.0
```
