### ISSUE TITLE
flutter stt

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#285]
插件

```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  speech_to_text: ^1.1.0
```
