### ISSUE TITLE
css

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#51]
css triangle:
https://css-tricks.com/snippets/css/css-triangle/
一个高宽均为0的div, 定义三个border, 其中两个border为transparent, 链接中的动画完美演示了为什么要这么做?

HTML

You can make them with a single div. It's nice to have classes for each direction possibility.
```html
<div class="arrow-up"></div>
<div class="arrow-down"></div>
<div class="arrow-left"></div>
<div class="arrow-right"></div>
```
#
CSS

The idea is a box with zero width and height. The actual width and height of the arrow is determined by the width of the border. In an up arrow, for example, the bottom border is colored while the left and right are transparent, which forms the triangle.
```css
.arrow-up {
  width: 0; 
  height: 0; 
  border-left: 5px solid transparent;
  border-right: 5px solid transparent;
  
  border-bottom: 5px solid black;
}

.arrow-down {
  width: 0; 
  height: 0; 
  border-left: 20px solid transparent;
  border-right: 20px solid transparent;
  }
```
  border-top: 20px solid #f00;
}

**Comment by uniquejava** [comment]
### css triangle

https://css-tricks.com/snippets/css/css-triangle/
一个高宽均为0的div, 定义三个border, 其中两个border为transparent, 链接中的动画完美演示了为什么要这么做?

HTML

You can make them with a single div. It's nice to have classes for each direction possibility.

``` html
<div class="arrow-up"></div>
<div class="arrow-down"></div>
<div class="arrow-left"></div>
<div class="arrow-right"></div>
```

#
CSS

The idea is a box with zero width and height. The actual width and height of the arrow is determined by the width of the border. In an up arrow, for example, the bottom border is colored while the left and right are transparent, which forms the triangle.

``` css
.arrow-up {
  width: 0; 
  height: 0; 
  border-left: 5px solid transparent;
  border-right: 5px solid transparent;

  border-bottom: 5px solid black;
}

.arrow-down {
  width: 0; 
  height: 0; 
  border-left: 20px solid transparent;
  border-right: 20px solid transparent;
  border-top: 20px solid #f00;
}

.arrow-left {
  width: 0; 
  height: 0; 
  border-top: 10px solid transparent;
  border-bottom: 10px solid transparent; 
  
  border-right:10px solid blue; 
}

.arrow-right {
  width: 0; 
  height: 0; 
  border-top: 60px solid transparent;
  border-bottom: 60px solid transparent;
  
  border-left: 60px solid green;
}
```

等边三角形: For an equilateral triangle it's worth pointing out that the height is 86.6% of the width so (border-left-width + border-right-width) \* 0.866% = border-bottom-width

**Comment by uniquejava** [comment]
## css outline
在border之外, 不占据任何空间(可以理解outline是贴在border之外的一层边), 他不会对页面中的任何元素位置产生影响.
在chrome中设置textarea/input的outline为0, 可以去掉focus后的蓝色高亮效果.

https://css-tricks.com/almanac/properties/o/outline/
http://w3school.com.cn/cssref/pr_outline.asp

**Comment by uniquejava** [comment]
## box shadow

[CSS3 Box Shadow on Top, Left, and Right Only][1]


[1]: https://stackoverflow.com/questions/4909561/css3-box-shadow-on-top-left-and-right-only

## no wrap
```css
white-space: nowrap;
```
或者使用bootstrap自带的`text-nowrap`样式.

## 文本溢出自动截断
```css
overflow: hidden;  // 重要
white-space: nowrap;  // 重要
text-overflow: ellipsis;  // 重要
display: block | inline-block // 重要
width|max-width: 250px    // 重要
```
还要设置其max-width:100%、看情况设定其父元素的max-width:100%

## sticker footer
[Sticky Footer, Five Ways](https://css-tricks.com/couple-takes-sticky-footer/)

## border length
见[Any way to limit border length?](https://stackoverflow.com/questions/4131490/any-way-to-limit-border-length)
### 方法一
```css
#mainDiv {
  height: 100px;
  width: 80px;
  position: relative;
  border-bottom: 2px solid #f51c40;
  background: #3beadc;
}

#borderLeft {
  border-left: 2px solid #f51c40;
  position: absolute;
  top: 50%;
  bottom: 0;
}
```
```html
<div id="mainDiv">
  <div id="borderLeft"></div>
</div>
```

### 方法二
```css
div {
  position: relative;
} 
/* Main div for border to extend to 50% from bottom left corner */
div:after {
  content:""; 
  background: black; 
  position: absolute; 
  bottom: 0; 
  left: 0; 
  height: 50%; 
  width: 1px;
}
```
(note - the `content: ""`; declaration is necessary in order for the pseudo-element to render)

**Comment by uniquejava** [comment]
## Flex

[Always equal flexbox columns](http://www.sumnoise.com/2016/04/06/equal-width-flexbox-columns/)

Assigning equal `flex-grow` values to flex-items will ensure those items are of equal width up to the point that their inner text content is larger than that width.

It’s pretty easy to get an [equal-width column grid layout going using flexbox](http://output.jsbin.com/ziyetaf):

```html
<div class="flex-container">
  <div class="flex-item"></div>
  <div class="flex-item"></div>
  <div class="flex-item"></div>
</div>
```

```css
.flex-container {
  display: flex;
}

.flex-item {
  flex: 1;
  margin-right: 10px;

  &:last-child {
    margin-right: 0;
  }
}
```

However, the preferred width of a flex-item containing text seems to be the text without line breaks, so one long word can ruin your whole day.

To prevent this from happening, just add `width: 0` to the flex-items. It’s then obviously up to you to handle how the text should flow, but at least the layout behaves consistently.
```css
.flex-container {
  display: flex;
}

.flex-item {
  flex: 1;
  width: 0; // Force equal-width columns
  margin-right: 10px;

  &:last-child {
    margin-right: 0;
  }
}
```

**Comment by uniquejava** [comment]
## 媒体查询 css3 media query
mq
```
@media (max-width: $var$px) {
  $END$
}
```

## 象素单位 px, em and rem 比较

I have two simple rules:

1. Size in `em` if the property scales according to it’s `font-size`
2. Size everything else in `rem.`

详见:  
1. [REM vs EM – The Great Debate](https://zellwk.com/blog/rem-vs-em/)
2. [PX, EM or REM Media Queries?](https://zellwk.com/blog/media-query-units/)

## 自定义字体 Custom Fonts 
[Defining Custom Fonts in CSS With @font-face and font-display](https://alligator.io/css/font-face/)

1. [SourceHanSans 下载](https://github.com/tkiapril/source-fonts)
2. otf转ttf: https://convertio.co/otf-ttf/
3. npm install -g ttf2eot && ttf2eot IBMPlexSans-Light-V01.1.ttf IBMPlexSans-Light-V01.1.eot
4. 定义css

```css
@font-face {
  font-family: IBMPlexSans Light;
  src: url(/assets/fonts/IBMPlexSans-Light-V01.1.ttf), url(/assets/fonts/IBMPlexSans-Light-V01.1.eot);
  font-display: swap;
}
```

使用font-spider压缩字体文件(将字体文件中不使用的文字全部删除)

[前端：使用第三方字体的缺点以及折中的优化](https://www.jianshu.com/p/5166843ca015)

**Comment by uniquejava** [comment]
## vertical-align

仅用于上下对齐 `同一行` 中的元素.
https://css-tricks.com/almanac/properties/v/vertical-align/

配合ghost-element技术也能用于元素的垂直居中.

## 给flex子元素加固定间距

下拉框自适应宽度，间距为10px

![image](https://user-images.githubusercontent.com/1049271/63215321-6f971a80-c157-11e9-8906-2e3fac59383a.png)

[Better way to set distance between flexbox items](https://stackoverflow.com/questions/20626685/better-way-to-set-distance-between-flexbox-items)

```css
.flexbox {
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: space-between;
}

.flexbox > * {
  /*
    1/3  - 3 columns per row
    10px - spacing between columns
  */
  box-sizing: border-box;
  width: calc(1 / 3 * 100% - (1 - 1 / 3) * 10px);
}
```

**Comment by uniquejava** [comment]
## 给background-image加滤镜
![image](https://user-images.githubusercontent.com/1049271/63214899-1330fc80-c151-11e9-85d0-938c2a8460ef.png)

[How to apply a CSS filter to a background image](https://stackoverflow.com/questions/20039765/how-to-apply-a-css-filter-to-a-background-image)
注意：需要从结构上拆分成两个Element， 将image放在一层， text放在image之上。如果不分层直接用filter文字也会变暗.

```vue
<div class="members">
  <a-avatar v-for="i in memberCount" :key="i" :src="require('@/assets/boy.jpeg')" />
  <span class="last-avatar-container">
    <div class="last-avatar-image" :style="{ backgroundImage: 'url(' + img + ')' }"></div>
    <div class="plus-text">+10</div>
  </span>
  <span class="total">共有 {{ team.member }}个</span>
</div>
<script>
export default {
  props: ['team'],
  data() {
    return {
      img: require('@/assets/boy.jpeg'),
    }
  },
  computed: {
    memberCount() {
      return this.team.member > 5 ? 4 : this.team.member - 1
    },
  },
}
</script>
```

```css
.last-avatar-container {
  position: relative;
  width: 30px;
  height: 30px;
  display: inline-block;
  vertical-align: bottom;

  margin-left: -11px;

  .last-avatar-image {
    position: absolute;
    left: 0;
    right: 0;
    top: 0;
    bottom: 0;
    background-size: cover;
    border-radius: 50%;
    border: solid #fff 1px;
    filter: brightness(0.47);
  }

  .plus-text {
    position: absolute;
    left: 50%;
    top: 50%;

    font-family: PingFangSC-Medium;
    font-size: 12px;
    color: #ffffff;
    letter-spacing: 0;

    transform: translate(-50%, -50%);
  }
}
```

**Comment by uniquejava** [comment]
## 选中第一个后代

```css
:not(.example) .example
```

see https://stackoverflow.com/a/12922863

## vue深度选择器 less + ant design
可以加scoped
```css
  .workarea ::v-deep .piggy.ant-tabs {
    background: #f6f6f8;

  >>> .piggy.ant-tabs {
    background: #f6f6f8;
```

## vue深度选择器 scss + element_ui
不能加scoped

```css
.parentCssName /deep/ .libCssName{}

```
## 使用::before设置背景图片

![image](https://user-images.githubusercontent.com/1049271/63407491-37296200-c41f-11e9-8c3f-d4fd66bfcfbb.png)


```css
.with-semitrans-bg {
	position: relative;
	height: 10rem;
	padding: 1rem;
	font-size: 2rem;
	color: #000;
	z-index: 1;
}

.with-semitrans-bg:before {
	content: "";
	position: absolute;
	width: 100%;
	height: 100%;
	top: 0;
	left: 0;
	background-image: url(https://wpshout.com/media/2016/04/converse-fields-768x574.jpg);
	background-position: center;
	background-size: cover;
	opacity: .5;
	z-index: -1;
}
```

```html
<div class="with-semitrans-bg">This <em>is</em> what we want.</div
```

原文：[Three Practical Uses of the :before and :after CSS Pseudoselectors](https://wpshout.com/three-practical-uses-css-pseudoselectors/)
