### ISSUE TITLE
bluemix

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#76]
## flask machine learning
https://github.com/snowch/flask-machine-learning

**Comment by uniquejava** [comment]
## 发布spring boot的
```
---
applications:
- instances: 1
  timeout: 180
  name: xxx
  buildpack: java_buildpack
  path: ./target/xxx-1.0-SNAPSHOT.jar
  memory: 512MB
  domain: au-syd.mybluemix.net
  host: xxx
  env:
    spring.profiles.active: dev
  
```
