### ISSUE TITLE
semantic ui

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#87]
segments > segment可以做成表格线的样子

表格
https://semantic-ui.com/collections/table.html

日历控件(简单好用)
https://github.com/mdehoog/Semantic-UI-Calendar
```js
$(document).ready(function () {
    $('select.dropdown').dropdown();

    $('#example2').calendar({
        type: 'date',
        formatter: {
            date: function (date, settings) {
                if (!date) return '';
                var day = date.getDate();
                var month = date.getMonth() + 1;
                var year = date.getFullYear();
                return year + '-' + month + '-' + day;
            }
        }
    });
});
```

**Comment by uniquejava** [comment]
## popup
```html
<div class="chat">
    <div class="wechat ui button" id="btnWechat"></div>
    <div class="weibo"></div>
</div>
```

```js
$('#btnWechat')
    .popup({
        html: '<img src="assets/images/qrcode.png">',
        position: 'top center',
        offset: -101
    });
```

**Comment by uniquejava** [comment]
## form validation

http://stackoverflow.com/questions/30033396/listen-to-semantic-ui-form-validation-errors-before-submit

**Comment by uniquejava** [comment]
##  得把.actions(.approve button)放到 modal 的 <form>下面, 即(content area中)
不然的话api(serializeForm:true)将不起作用, 这是因为semantic会去找离.approve.button最近的那个form, 所以必须放在form下 此时得修改.actions的样式如下 :
```scss
/* To use ajax file upload I have to move .actions inside modal content area */
.ui.modal .actions {
  border-top: none;
  background-color: #f0f9ff;
  padding: 1rem;
  text-align: right;

  margin: 0 -1.5rem -1.5rem;

  border-bottom-left-radius: .28571429rem;
  border-bottom-right-radius: .28571429rem;

  .button {
    font-weight: 300;
    margin-left: .75em;
  }

  .ui.approve.button {
    color: #ffffff;
    background-color: #289adb;
  }

  .ui.cancel.button {
    color: #289adb;
    background-color: #ffffff;
  }
}
```

或者是否可以将form作为ui.modal的孩子.? 需要试一下.
