### ISSUE TITLE
css list-style奇技淫巧

### ISSUE THREAD

**Issue by uniquejava** [uniquejava/blog#99]
https://stackoverflow.com/questions/18397437/css-list-li-dot-one-color-text-another-color-css-only

目前我是用css自已定义的小圆点.(可以方便的使用background属性切换color)

在html中这样使用:
```html
<ul *ngIf="i == 0">
  <li *ngFor="let name of names; let j = index" [ngClass]="{'highlight': j==0}">
    <i class="dot" [ngStyle]="{'background': mycolor}"></i>
    <span>{{name}}</span>
  </li>
</ul>
```
在scss中这样定义样式:
```scss
ul {
  margin: 0;
  padding-left: 2em;

  li {
    color: #444;
    list-style: none;
    line-height: 2em;

    & > * {
      vertical-align: middle;
    }
  }

  li:before {
    content: ' ';
    width: 6px;
    display: inline-block;
  }

  i.dot {
    background: orange;
    display: inline-block;
    height: 0.6em;
    width: 0.6em;
    border-radius: 50%;
  }

}
```
